Repository FRONT-END-BOOTCAMP-PLUS-5/itGun, pull requests merged in 2025-08, with the labels that each got.

#9 chore: 이슈 템플릿에 name, about 필드 추가
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: docs, chore

#14 fix: badge 목록 조회 api 메소드 변경
  app/api/user/badges/route.ts
Labels: chore, BE

#17 사용자 정보 수정 API 개발
  app/api/user/info/.gitkeep
  app/api/user/info/route.ts
  backend/application/user/info/dtos/.gitkeep
  backend/application/user/info/dtos/UpdateUserInfoDto.ts
  backend/application/user/info/usecases/.gitkeep
  backend/application/user/info/usecases/UpdateUserInfoUsecase.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/PrUserRepository.ts
Labels: feat, BE

#23 운동 기록 데이터 등록 및 게이지 계산 구현
  app/api/user/logs/.gitkeep
  app/api/user/logs/route.ts
  backend/application/user/logs/dtos/.gitkeep
  backend/application/user/logs/dtos/CreateLogRequestDto.ts
  backend/application/user/logs/dtos/CreateLogResponseDto.ts
  backend/application/user/logs/services/BodyPartGaugeCalculator.ts
  backend/application/user/logs/services/BodyPartGaugeConstants.ts
  backend/application/user/logs/usecases/.gitkeep
  backend/application/user/logs/usecases/CreateLogUsecase.ts
  backend/domain/repositories/BodyPartGaugeRepository.ts
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
  backend/infrastructure/repositories/PrLogRepository.ts
  backend/infrastructure/repositories/PrLogWorkoutRepository.ts
  backend/infrastructure/repositories/PrWorkoutRepository.ts
Labels: feat, BE

#28 회원 탈퇴 API 개발
  app/api/user/info/route.ts
  backend/application/user/info/dtos/DeleteUserDto.ts
  backend/application/user/info/usecases/DeleteUserUsecase.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/PrUserRepository.ts
Labels: feat, BE

#32 [GET] 월별 사용자 로그 조회 API 구현
  app/api/user/logs/route.ts
  backend/application/user/logs/dtos/GetLogDto.ts
  backend/application/user/logs/dtos/GetUserLogsQueryDto.ts
  backend/application/user/logs/dtos/GetUserLogsRequestDto.ts
  backend/application/user/logs/dtos/GetUserLogsResponseDto.ts
  backend/application/user/logs/dtos/GetWorkoutDto.ts
  backend/application/user/logs/usecases/GetUserLogListUsecase.ts
  backend/domain/entities/Log.ts
  backend/domain/entities/LogWorkout.ts
  backend/domain/entities/Workout.ts
  backend/domain/repositories/LogRepository.ts
  backend/infrastructure/repositories/PrLogRepository.ts
Labels: feat, BE

#37 Feat/5 회원 정보 조회
  app/api/user/info/route.ts
  backend/application/user/info/dtos/GetUserInfoRequestDto.ts
  backend/application/user/info/dtos/GetUserInfoResponseDto.ts
  backend/application/user/info/usecases/GetUserInfoUsecase.ts
  backend/infrastructure/repositories/PrUserRepository.ts
Labels: feat, BE

#35 회원가입/로그인 API 및 NextAuth 인증 시스템 구현
  .github/workflows/ci.yml
  app/api/auth/[...nextauth]/auth.ts
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/verify/route.ts
  app/api/signin/.gitkeep
  app/api/signout/.gitkeep
  app/api/signup/.gitkeep
  app/layout.tsx
  app/providers.tsx
  backend/application/signin/dtos/.gitkeep
  backend/application/signin/dtos/SignInRequestDto.ts
  backend/application/signin/dtos/SignInResponseDto.ts
  backend/application/signin/usecases/.gitkeep
  backend/application/signin/usecases/SignInUsecase.ts
  backend/application/signup/dtos/.gitkeep
  backend/application/signup/dtos/CreateUserRequestDto.ts
  backend/application/signup/dtos/CreateUserResponseDto.ts
  backend/application/signup/usecases/.gitkeep
  backend/application/signup/usecases/CreateUserUsecase.ts
  backend/domain/repositories/TokenRepository.ts
  backend/domain/repositories/UserRepository.ts
  backend/infrastructure/repositories/JwtTokenRepository.ts
  backend/infrastructure/repositories/PrUserRepository.ts
  package.json
  pnpm-lock.yaml
  types/next-auth.d.ts
  utils/auth.ts
Labels: feat, BE

#45 docs: #44 exercise 디테일 영한 번역 작업 파일
  static/exercises/exercises-data-ko.json
Labels: docs

#49 [디자인시스템] Icon 컴포넌트 개발
  ds/components/atoms/icon/.gitkeep
  ds/components/atoms/icon/Icon.stories.ts
  ds/components/atoms/icon/Icon.tsx
  ds/components/atoms/icon/Icon.types.ts
  static/svgs/svgList.tsx
Labels: feat, FE

#50 [디자인시스템] Text 공통 컴포넌트 개발
  ds/components/atoms/text/Text.stories.tsx
  ds/components/atoms/text/Text.tsx
  ds/components/atoms/text/Text.types.ts
  ds/components/atoms/text/TextWrapper.tsx
  ds/styles/tokens/text/variants.ts
Labels: feat, FE

#53 [디자인시스템] Button 공통 컴포넌트 개발
  ds/components/atoms/button/.gitkeep
  ds/components/atoms/button/Button.stories.tsx
  ds/components/atoms/button/Button.tsx
  ds/components/atoms/button/Button.types.ts
  ds/styles/tokens/button/sizes.ts
  ds/styles/tokens/button/variants.ts
Labels: feat, FE

#61 인증시스템 및 middleware
  app/api/auth/[...nextauth]/auth.ts
  app/api/auth/verify/route.ts
  app/layout.tsx
  app/providers.tsx
  app/providers/NextAuthSessionProviders.tsx
  backend/application/signin/dtos/SignInResponseDto.ts
  backend/application/signin/usecases/SignInUsecase.ts
  backend/application/signup/dtos/CreateUserResponseDto.ts
  backend/application/signup/usecases/CreateUserUsecase.ts
  backend/domain/repositories/TokenRepository.ts
  backend/infrastructure/repositories/JwtTokenRepository.ts
  middleware.ts
  tsconfig.json
  types/next-auth.d.ts
  utils/auth.ts
Labels: feat, BE

#66 [디자인시스템] Input 컴포넌트 개발
  ds/components/atoms/icon/Icon.stories.ts
  ds/components/atoms/input/.gitkeep
  ds/components/atoms/input/Input.stories.tsx
  ds/components/atoms/input/Input.tsx
  ds/components/atoms/input/Input.types.ts
  ds/styles/tokens/input/sizes.ts
  static/svgs/svgList.tsx
Labels: feat, FE

#72 [DB] UserRecord 테이블 컬럼별 개별 테이블로 분리
  app/api/user/logs/route.ts
  backend/application/user/logs/services/BadgeAchievementService.ts
  backend/application/user/logs/usecases/CreateLogUsecase.ts
  backend/domain/entities/BenchPressRecord.ts
  backend/domain/entities/BigThreeRecord.ts
  backend/domain/entities/DeadliftRecord.ts
  backend/domain/entities/RunningRecord.ts
  backend/domain/entities/SquatRecord.ts
  backend/domain/entities/UserRecord.ts
  backend/domain/repositories/UserRecordRepository.ts
  backend/infrastructure/repositories/PrUserRecordRepository.ts
  prisma/schema.prisma
Labels: refactor, BE

#92 운동기록 및 운동 기록 삭제 API 리팩토링
  app/api/user/logs/[id]/route.ts
  app/api/user/logs/route.ts
  backend/application/user/logs/constants/badgeConstants.ts
  backend/application/user/logs/services/BadgeAchievementService.ts
  backend/application/user/logs/services/BadgeDeletionService.ts
  backend/application/user/logs/services/badge-achievement/ConsecutiveDaysBadgeService.ts
  backend/application/user/logs/services/badge-achievement/FirstWorkoutBadgeService.ts
  backend/application/user/logs/services/badge-achievement/RecordBadgeService.ts
  backend/application/user/logs/services/badge-achievement/WeeklyWorkoutBadgeService.ts
  backend/application/user/logs/usecases/CreateLogUsecase.ts
  backend/application/user/logs/usecases/DeleteLogUsecase.ts
  backend/domain/repositories/LogRepository.ts
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
  backend/infrastructure/repositories/PrLogRepository.ts
Labels: refactor, BE

#99 [디자인시스템] Toast 컴포넌트 width 수정
  ds/components/molecules/toast/Toast.tsx
Labels: fix, FE

#102 [페이지] 메인페이지
  app/api/user/badges/route.ts
  app/api/user/character/route.ts
  app/components/BadgeRing.tsx
  app/components/MainCharacter.tsx
  app/components/MainUserTitle.tsx
  app/components/MobileNavBar.tsx
  app/layout.tsx
  app/page.tsx
  backend/application/user/character/dtos/GetUserCharacterDto.ts
  backend/application/user/character/dtos/GetUserCharacterQueryDto.ts
  backend/application/user/character/usecases/GetUserCharacterUsecase.ts
  backend/domain/entities/CharacterAsset.ts
  backend/domain/repositories/CharacterAssetRepository.ts
  backend/infrastructure/repositories/PrCharacterAssetRepository.ts
  ds/components/atoms/character/Character.stories.tsx
  ds/components/atoms/character/Character.tsx
  ds/components/atoms/character/Character.types.ts
  ds/components/atoms/icon/Icon.tsx
  ds/components/atoms/icon/Icon.types.ts
  ds/styles/globals.css
  hooks/useGetUserBadges.ts
  hooks/useGetUserCharacter.ts
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  services/user/badges/getUserBadges.ts
  services/user/character/getUserCharacter.ts
  static/svgs/svgList.tsx
  utils/animations.ts
  utils/assets.ts
Labels: feat, FE, BE

#103 [디자인시스템] Workout 컴포넌트 개발
  ds/components/molecules/workout/.gitkeep
  ds/components/molecules/workout/Workout.stories.tsx
  ds/components/molecules/workout/Workout.tsx
  ds/components/molecules/workout/Workout.types.ts
  ds/styles/tokens/workout/fields.ts
  ds/styles/tokens/workout/gridColumns.ts
  ds/styles/tokens/workout/variants.ts
  ds/styles/tokens/workout/width.ts
Labels: feat, FE

#107 [페이지] 로딩페이지
  app/components/loading/LoadingCharacter.tsx
  app/components/loading/LoadingText.tsx
  app/loading.tsx
  static/svgs/burky.tsx
  utils/character.ts
Labels: feat, FE

#116 [페이지] 뱃지 조회 페이지
  app/components/BadgeRing.tsx
  app/user/badges/components/BadgeItem.tsx
  app/user/badges/components/BadgeItem.type.ts
  app/user/badges/components/BageGrid.tsx
  app/user/badges/components/Title.tsx
  app/user/badges/page.tsx
Labels: feat, FE

#118 feat: #40 드롭다운 수정하기
  ds/components/molecules/dropdown/Dropdown.stories.tsx
  ds/components/molecules/dropdown/Dropdown.tsx
  ds/components/molecules/dropdown/Dropdown.types.ts
  ds/styles/tokens/dropdown/size.ts
  static/svgs/svgList.tsx
Labels: feat, FE

#120 [GET] 개별 운동 로그 조회 API
  app/api/user/logs/[id]/route.ts
  backend/application/user/logs/dtos/GetLogRequestDto.ts
  backend/application/user/logs/dtos/GetLogResponseDto.ts
  backend/application/user/logs/usecases/DeleteLogUsecase.ts
  backend/application/user/logs/usecases/GetLogUsecase.ts
  backend/domain/repositories/LogRepository.ts
  backend/infrastructure/repositories/PrLogRepository.ts
Labels: feat, BE

#128 [디자인시스템] header 컴포넌트 max-width `inherit` 적용
  ds/components/molecules/header/Header.tsx
Labels: fix, FE

#131 [페이지] 근육 성장률 조회 페이지
  app/components/MainCharacter.tsx
  app/components/MainCharacter.type.ts
  app/components/title/Title.tsx
  app/components/title/Title.type.ts
  app/user/badges/components/Title.tsx
  app/user/badges/page.tsx
  app/user/gauges/components/GaugeItem.tsx
  app/user/gauges/components/GaugeItem.types.ts
  app/user/gauges/components/GaugeList.tsx
  app/user/gauges/page.tsx
  backend/application/user/gauges/dtos/GetUserGaugeResponseDto.ts
  backend/application/user/gauges/usecases/GetUserGaugeUsecase.ts
  hooks/useGetUserGauges.ts
  services/user/gauges/getUserGauges.ts
Labels: feat, FE

#133 [페이지] 회원가입
  app/api/user/email/route.ts
  app/landing/components/AuthFooter.tsx
  app/layout.tsx
  app/signup/[steps]/components/Step1Form.tsx
  app/signup/[steps]/components/Step2Form.tsx
  app/signup/[steps]/components/Step3Form.tsx
  app/signup/[steps]/components/ValidationItem.tsx
  app/signup/[steps]/page.tsx
  app/signup/context/SignupContext.tsx
  app/signup/context/SignupContext.types.ts
  app/signup/layout.tsx
  app/signup/page.tsx
  backend/application/signout/dtos/.gitkeep
  backend/application/signout/usecases/.gitkeep
  backend/application/user/email/dtos/CheckEmailRequestDto.ts
  backend/application/user/email/dtos/CheckEmailResponseDto.ts
  backend/application/user/email/usecases/CheckEmailUsecase.ts
  ds/components/molecules/dropdown/Dropdown.tsx
  services/user/checkEmail.ts
Labels: feat, FE

#134 미들웨어 하위 경로 보안 검사 누락 수정
  middleware.ts
Labels: fix, BE

#135 [페이지] 운동 기록 상세 조회 페이지 개발
  app/user/logs/[id]/components/LogCharacter.tsx
  app/user/logs/[id]/components/LogDetailPage.tsx
  app/user/logs/[id]/components/LogSummaryHeader.tsx
  app/user/logs/[id]/components/WorkoutList.tsx
  app/user/logs/[id]/page.tsx
  app/user/logs/[id]/types.ts
  ds/components/molecules/dialog/Dialog.tsx
  ds/components/molecules/toast/Toast.tsx
  ds/components/molecules/workout/Workout.tsx
  hooks/useDeleteUserLog.ts
  hooks/useGetUserLog.ts
  services/user/logs/deleteUserLog.ts
  services/user/logs/getUserLog.ts
  utils/dateToYmdSlash.ts
  utils/dateToyymmdd.ts
Labels: feat, FE

#141 로그인 페이지 컴포넌트 분리 및 레이아웃 수정
  app/signin/components/SigninForm.tsx
  app/signin/page.tsx
Labels: refactor, FE

#145 MainCharacter 컴포넌트 props date추가
  app/components/MainCharacter.tsx
  app/components/MainCharacter.type.ts
  app/user/logs/[id]/components/LogCharacter.tsx
  app/user/logs/[id]/components/LogDetailPage.tsx
  hooks/useGetUserCharacter.ts
Labels: refactor, FE

#163 log 목록 조회 중 상태 초기화 문제 해결
  app/user/logs/components/CalendarHeader.tsx
  app/user/logs/components/LogList.tsx
  app/user/logs/page.tsx
  app/user/logs/types.ts
  hooks/useGetUserLogs.ts
Labels: fix, refactor, FE

#172 [QA] 특정 날짜의 캐릭터 조회 시 오류 해결
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
Labels: fix, BE

#177 [QA] 메뉴 페이지 하단 여백 수정
  app/menus/page.tsx
Labels: fix, FE

#178 [QA] 운동조회 페이지 - get api 수정
  app/exercises/components/constants.ts
  backend/infrastructure/repositories/PrExerciseRepository.ts
Labels: fix, chore, BE

#180 [QA] 게이지 페이지 하단 여백 수정
  app/user/gauges/page.tsx
Labels: chore, FE

#187 [QA] 프로그레스 바 배경 색 수정
  ds/components/molecules/progressBar/ProgressBar.tsx
Labels: chore, FE

#189 [QA] 운동기록 관련
  backend/application/exercises/dtos/GetExerciseListReponseDto.ts
  backend/application/exercises/usecases/GetExerciseListUsecase.ts
  backend/application/user/logs/utils/bodyPartGaugeCalculator.ts
Labels: fix, BE

#191 [QA] logs & exercises 페이지
  app/exercises/components/ExerciseItem.tsx
  app/exercises/components/ExerciseList.tsx
  app/exercises/components/SearchInput.tsx
  app/exercises/page.tsx
  app/logs/components/AddWorkoutForm.tsx
  app/logs/components/DateTimeInput.tsx
  app/logs/components/ExerciseListModal.tsx
  app/logs/components/WorkoutTypeSelector.tsx
  app/user/logs/page.tsx
  ds/components/molecules/workout/Workout.tsx
  services/exercises/getExercises.ts
Labels: fix, FE

#198 [페이지] 최근 14일이내 운동 기록 없을 경우 메인페이지 캐릭터 반응 추가
  app/components/MainCharacter.tsx
  app/components/MainCharacter.type.ts
  app/components/MainPage.tsx
  hooks/useCheckUserGauge.ts
Labels: feat, FE

#199 [페이지] 메인페이지 캐릭터 이미지 다운로드 기능 추가
  app/components/CharacterDownloadButton.tsx
  app/components/CharacterDownloadButton.type.ts
  app/components/MainUserTitle.tsx
  utils/downloadCharacter.ts
Labels: feat, FE

#201 [QA] 최신 게이지 조회 api fix
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
Labels: fix, BE

#202 [QA] 운동기록 페이지 2차 qa 이슈 해결
  app/exercises/components/SearchInput.tsx
  app/logs/components/DateTimeInput.tsx
  app/logs/components/WorkoutLogSaveButton.tsx
  app/logs/components/type.ts
  app/logs/page.tsx
  ds/components/molecules/workout/Workout.tsx
  services/user/logs/createUserLogs.ts
  utils/api/apiClient.ts
Labels: fix, FE

#204 [QA] 로그인, 회원가입, 메인 페이지 height 조정
  app/layout.tsx
Labels: fix, FE

#207 Release/v0.1.2
  app/components/CharacterDownloadButton.tsx
  app/components/CharacterDownloadButton.type.ts
  app/components/MainCharacter.tsx
  app/components/MainCharacter.type.ts
  app/components/MainPage.tsx
  app/components/MainUserTitle.tsx
  app/exercises/components/SearchInput.tsx
  app/layout.tsx
  app/logs/components/DateTimeInput.tsx
  app/logs/components/WorkoutLogSaveButton.tsx
  app/logs/components/type.ts
  app/logs/page.tsx
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
  ds/components/molecules/workout/Workout.tsx
  hooks/useCheckUserGauge.ts
  services/user/logs/createUserLogs.ts
  utils/api/apiClient.ts
  utils/downloadCharacter.ts
Labels: release

#216 [QA] 근로그 페이지 로그 목록 크기 조절
  app/user/logs/components/LogItem.tsx
  app/user/logs/components/LogList.tsx
  app/user/logs/page.tsx
  app/user/logs/types.ts
  ds/styles/globals.css
Labels: fix, refactor, FE

#219 [QA] 임시 수정-캐릭터 get api 에 date param있는 경우
  backend/infrastructure/repositories/PrBodyPartGaugeRepository.ts
Labels: fix, BE

#220 [QA]운동기록 페이지 3차 qa 오류 수정
  app/exercises/components/ExerciseList.tsx
  app/logs/components/AddWorkoutForm.tsx
  app/logs/components/DateTimeInput.tsx
  app/logs/components/type.ts
  app/logs/page.tsx
  app/logs/types.ts
Labels: fix, FE

#226 [QA] 신기록 관련 테이블 userId 컬럼 unique 제약 조건 제거
  prisma/schema.prisma
Labels: fix, BE

#229 [QA]운동 기록 페이지 3차 qa 오류 수정 최종
  app/exercises/components/ExerciseList.tsx
  app/logs/components/AddWorkoutForm.tsx
  app/logs/components/WorkoutLogSaveButton.tsx
  app/logs/components/type.ts
  app/logs/page.tsx
  app/logs/types.ts
  ds/components/molecules/workout/Workout.tsx
  ds/components/molecules/workout/Workout.types.ts
Labels: fix, FE

#231 랜딩페이지에 보여질 이미지 추가
  app/landing/components/IntroCarousel.tsx
  static/images/itgun1.png
  static/images/itgun2.png
  static/images/itgun3.png
  static/images/itgun4.png
  static/images/itgun5.png
Labels: chore, FE

#235 운동 상세 정보 모달 상단 여백 추가
  app/components/ModalContainer.tsx
  app/menus/components/MenuHeader.tsx
Labels: FE

#237 Release/v0.1.4
  app/components/ModalContainer.tsx
  app/exercises/components/ExerciseList.tsx
  app/landing/components/IntroCarousel.tsx
  app/logs/components/AddWorkoutForm.tsx
  app/logs/components/WorkoutLogSaveButton.tsx
  app/logs/components/type.ts
  app/logs/page.tsx
  app/logs/types.ts
  app/menus/components/MenuHeader.tsx
  backend/application/user/logs/services/BadgeDeletionService.ts
  backend/domain/repositories/BenchPressRecordRepository.ts
  backend/domain/repositories/BigThreeRecordRepository.ts
  backend/domain/repositories/DeadliftRecordRepository.ts
  backend/domain/repositories/RunningRecordRepository.ts
  backend/domain/repositories/SquatRecordRepository.ts
  backend/domain/repositories/UserBadgeRepository.ts
  backend/infrastructure/repositories/PrBenchPressRecordRepository.ts
  backend/infrastructure/repositories/PrBigThreeRecordRepository.ts
  backend/infrastructure/repositories/PrDeadliftRecordRepository.ts
  backend/infrastructure/repositories/PrRunningRecordRepository.ts
  backend/infrastructure/repositories/PrSquatRecordRepository.ts
  backend/infrastructure/repositories/PrUserBadgeRepository.ts
  ds/components/molecules/workout/Workout.tsx
  ds/components/molecules/workout/Workout.types.ts
  hooks/useCreateUserLogs.ts
  prisma/schema.prisma
  static/images/itgun1.png
  static/images/itgun2.png
  static/images/itgun3.png
  static/images/itgun4.png
  static/images/itgun5.png
Labels: release

#240 [QA] 런닝 신기록 최소 기준 수정
  backend/application/user/logs/constants/userRecordConstants.ts
Labels: fix, BE

#243 fix: #242 메인페이지 사용자 뱃지 가져오는 로직 수정
  backend/application/user/badges/usecases/GetUserBadgeListUsecase.ts
  backend/domain/repositories/UserBadgeRepository.ts
  backend/infrastructure/repositories/PrUserBadgeRepository.ts
Labels: fix, BE

#244 Release/v0.1.5
  backend/application/user/badges/usecases/GetUserBadgeListUsecase.ts
  backend/application/user/logs/constants/userRecordConstants.ts
  backend/domain/repositories/UserBadgeRepository.ts
  backend/infrastructure/repositories/PrUserBadgeRepository.ts
Labels: release
